version: 0.2
env:
  secrets-manager:
    DOCKERID: DOCKER_LOGIN_DETAILS:DockerId
    DOCKERPASS: DOCKER_LOGIN_DETAILS:DockerPassword

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 12
  pre_build:
    commands:      
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - echo $COMMIT_HASH
      - echo $REPOSITORY_URI
      - echo $DOCKERID
      - docker login -u $DOCKERID -p $DOCKERPASS
      
  build:
    commands:
      - echo Building React app...
      - npm install
      - npm run build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:$COMMIT_HASH .
 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push -a $REPOSITORY_URI